### ISSUE TITLE
Temp text renderer not rendering 

### ISSUE THREAD

**Issue by sxmxc** [TheRealNOIG/OrgPer#1]
PauseMenuScreen not rendering test text as it should. 

No errors  being thrown.

**Comment by TyGrze** [comment]
This is due to you using OpenGL1.0 which is outdated 
```C#
using OpenToolkit.Graphics.OpenGL;
```
```C#
GL.Begin(BeginMode.Quads);
GL.TexCoord2(0, 0);
GL.Vertex2(x, y);
GL.TexCoord2(1, 0);
GL.Vertex2(x + width, y);
GL.TexCoord2(1, 1);
GL.Vertex2(x + width, y + height);
GL.TexCoord2(0, 1);
 GL.Vertex2(x, y + height);
GL.End();
```
Here is a good video on how to do text in OpenGL4.0
https://www.youtube.com/watch?v=mnIQEQoHHCU
https://www.youtube.com/watch?v=d8cfgcJR9Tk

However, I think this should probably be done on a new branch.

**Comment by sxmxc** [comment]
I figured as much. Was thrown together in about 15 mins last night. Just put it here to remind myself to circle back.

**Comment by TyGrze** [comment]
Or we can just take this library that someone already made to render text in OpenTK
https://github.com/opcon/QuickFont
